
package vistas;

import conexion.Conexion;
import controlador.Ctrl_Producto;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import modelos.Producto;


public class FrmNuevoProducto extends javax.swing.JFrame {
    
    int obtenerIdCategoriaCombo = 0;
    public FrmNuevoProducto() {
        initComponents();
        this.setTitle("Nuevo Producto");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        categoria = new rojeru_san.rslabel.RSLabelBorderRound();
        nombre = new rojeru_san.rslabel.RSLabelBorderRound();
        cantidad = new rojeru_san.rslabel.RSLabelBorderRound();
        precio = new rojeru_san.rslabel.RSLabelBorderRound();
        descripcion = new rojeru_san.rslabel.RSLabelBorderRound();
        iva = new rojeru_san.rslabel.RSLabelBorderRound();
        txt_nombre = new rojeru_san.rsfield.RSTextField();
        txt_cantidad = new rojeru_san.rsfield.RSTextField();
        txt_precio = new rojeru_san.rsfield.RSTextField();
        txt_descripcion = new rojeru_san.rsfield.RSTextField();
        jComboBox_iva = new RSMaterialComponent.RSComboBoxMaterial();
        jComboBox_categoria = new RSMaterialComponent.RSComboBoxMaterial();
        jLabel1 = new javax.swing.JLabel();
        btn_volver = new rojeru_san.rsbutton.RSButtonForma();
        btn_guardar = new rojeru_san.rsbutton.RSButtonForma();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        categoria.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        categoria.setText("Categoria:");
        jPanel1.add(categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 120, 30));

        nombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nombre.setText("Nombre:");
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 120, 30));

        cantidad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cantidad.setText("Cantidad:");
        jPanel1.add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 120, 30));

        precio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        precio.setText("Precio:");
        jPanel1.add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 120, 30));

        descripcion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        descripcion.setText("Descripcion:");
        jPanel1.add(descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 120, 30));

        iva.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        iva.setText("Iva:");
        jPanel1.add(iva, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 120, 30));

        txt_nombre.setPlaceholder("");
        txt_nombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_nombreFocusLost(evt);
            }
        });
        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        jPanel1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 170, 20));

        txt_cantidad.setPlaceholder("");
        txt_cantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cantidadFocusLost(evt);
            }
        });
        txt_cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cantidadActionPerformed(evt);
            }
        });
        jPanel1.add(txt_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 170, 20));

        txt_precio.setPlaceholder("");
        txt_precio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_precioFocusLost(evt);
            }
        });
        txt_precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_precioActionPerformed(evt);
            }
        });
        jPanel1.add(txt_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 170, 20));

        txt_descripcion.setPlaceholder("");
        txt_descripcion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_descripcionFocusLost(evt);
            }
        });
        txt_descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_descripcionActionPerformed(evt);
            }
        });
        jPanel1.add(txt_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 170, 20));

        jComboBox_iva.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Iva:", "No grava iva", "19%" }));
        jPanel1.add(jComboBox_iva, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 170, 20));

        jComboBox_categoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione categoria:", "RSItem 2", "RSItem 3", "RSItem 4" }));
        jPanel1.add(jComboBox_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 170, 20));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nuevo Producto");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 210, -1));

        btn_volver.setText("Volver");
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });
        jPanel1.add(btn_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 120, 40));

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 120, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nombreFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreFocusLost

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void txt_cantidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cantidadFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cantidadFocusLost

    private void txt_cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cantidadActionPerformed

    private void txt_precioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_precioFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_precioFocusLost

    private void txt_precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_precioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_precioActionPerformed

    private void txt_descripcionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_descripcionFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_descripcionFocusLost

    private void txt_descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_descripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_descripcionActionPerformed

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
//        Menu menu = new Menu();
//        menu.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btn_volverActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        Producto producto = new Producto();
        Ctrl_Producto controlProducto = new Ctrl_Producto();
        String iva = "";
        String categoria = "";
        iva = jComboBox_iva.getSelectedItem().toString().trim();
        categoria = jComboBox_categoria.getSelectedItem().toString().trim();
        
        if(txt_nombre.getText().equals("") || txt_cantidad.getText().equals("") || txt_precio.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Completa todos los campos");
            txt_nombre.setBackground(Color.red);
            txt_cantidad.setBackground(Color.red);
            txt_precio.setBackground(Color.red);
            txt_descripcion.setBackground(Color.red);
        }else{
            if(!controlProducto.exiteProducto(txt_nombre.getText().trim())){
                
                if(iva.equalsIgnoreCase("Seleccione iva:")){
                   JOptionPane.showMessageDialog(null,"Seleccione iva.");
                }else{
                    if (categoria.equalsIgnoreCase("Seleccione categoria:")){
                        JOptionPane.showMessageDialog(null,"Seleccione categoria.");
                    }else{
                        try {
                            producto.setNombre(txt_nombre.getText().trim());
                            producto.setCantidad(Integer.parseInt(txt_cantidad.getText().trim()));
                            String precioTXT = "";
                            double Precio = 0.0;
                            precioTXT = txt_precio.getText().trim();
                            boolean aux = false;
                            
                            for (int i=0;i<precioTXT.length();i++){
                                if(precioTXT.charAt(i) == ','){
                                    String precioNuevo = precioTXT.replace(",",".");
                                    Precio = Double.parseDouble(precioNuevo);
                                    aux = true;
                                }
                                
                            }
                            if(aux == true){
                                producto.setPrecio_unitario(Precio);
                            }else{
                                Precio = Double.parseDouble(precioTXT);
                                producto.setPrecio_unitario(Precio);
                            }
                            producto.setDescripcion(txt_descripcion.getText().trim());
                            
                            if(iva.equalsIgnoreCase("No grava iva")){
                                producto.setProcentajeIva(0);
                            }else if(iva.equalsIgnoreCase("12%")){
                                producto.setProcentajeIva(12);
                            }else if(iva.equalsIgnoreCase("14%")){
                                producto.setProcentajeIva(14);
                            }
                            this.IdCategoria();
                            producto.setId_categoria(obtenerIdCategoriaCombo);
                            producto.setEstado(1);
                            if(controlProducto.guardar(producto)){
                                JOptionPane.showMessageDialog(null, "Registro Guardado");
                                txt_nombre.setBackground(Color.green);
                                txt_cantidad.setBackground(Color.green);
                                txt_precio.setBackground(Color.green);
                                txt_descripcion.setBackground(Color.green);
                                
                                this.CargarComboCategorias();
                                this.jComboBox_iva.setSelectedItem("");
                                this.Limpiar();
                            }else{
                                JOptionPane.showMessageDialog(null, "Error al Guardar");
                            }
                        } catch (HeadlessException | NumberFormatException e) {
                            System.out.println("Error en: " + e);
                        }
                    }
                }
                
            }else{
                JOptionPane.showMessageDialog(null,"El Producto ya existe");
            }
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmNuevoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmNuevoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmNuevoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmNuevoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmNuevoProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.rsbutton.RSButtonForma btn_guardar;
    private rojeru_san.rsbutton.RSButtonForma btn_volver;
    private rojeru_san.rslabel.RSLabelBorderRound cantidad;
    private rojeru_san.rslabel.RSLabelBorderRound categoria;
    private rojeru_san.rslabel.RSLabelBorderRound descripcion;
    private rojeru_san.rslabel.RSLabelBorderRound iva;
    private RSMaterialComponent.RSComboBoxMaterial jComboBox_categoria;
    private RSMaterialComponent.RSComboBoxMaterial jComboBox_iva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private rojeru_san.rslabel.RSLabelBorderRound nombre;
    private rojeru_san.rslabel.RSLabelBorderRound precio;
    private rojeru_san.rsfield.RSTextField txt_cantidad;
    private rojeru_san.rsfield.RSTextField txt_descripcion;
    private rojeru_san.rsfield.RSTextField txt_nombre;
    private rojeru_san.rsfield.RSTextField txt_precio;
    // End of variables declaration//GEN-END:variables
        private void Limpiar(){
        txt_nombre.setText("");
        txt_cantidad.setText("");
        txt_precio.setText("");
        txt_descripcion.setText("");
        
    }
    private void CargarComboCategorias(){
        Connection cn = Conexion.conectar();
        String sql = "select * from categoria";
        Statement st;
        try{
        
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            jComboBox_categoria.removeAllItems();
            jComboBox_categoria.addItem("Seleccione categoria");
            while(rs.next()){
                jComboBox_categoria.addItem(rs.getString("tipo_categoria"));
            }
            cn.close();
        }catch(SQLException e){
            System.out.println("Error al cargar producto");
        }
    }
    
    private int IdCategoria(){
        String sql = "select * from categoria where tipo_categoria = '"+this.jComboBox_categoria.getSelectedItem()+"'";
        Statement st;
        try {
            Connection cn = Conexion.conectar();
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                obtenerIdCategoriaCombo = rs.getInt("IdCategoria");
            }
        } catch (Exception e) {
            System.out.println("Error al obtener id categoria");
        }
        return obtenerIdCategoriaCombo;
    }
}
