
package vistas;

import controlador.Ctrl_Registro;
import java.awt.Dimension;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import modelos.Cliente;


public class InterDatos extends javax.swing.JInternalFrame {

    public static JDesktopPane jDesktopPane_menu;
    public InterDatos() {
        initComponents();
        this.setSize(new Dimension(695, 650));
        this.setTitle("Datos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valoresEnum1 = new rojeru_san.efectos.ValoresEnum();
        jPanel1 = new javax.swing.JPanel();
        txt_cedula = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Cant1 = new javax.swing.JTextField();
        Cant2 = new javax.swing.JTextField();
        Cant3 = new javax.swing.JTextField();
        Cant4 = new javax.swing.JTextField();
        item5 = new javax.swing.JTextField();
        vr5 = new javax.swing.JTextField();
        Cant5 = new javax.swing.JTextField();
        item1 = new javax.swing.JTextField();
        item2 = new javax.swing.JTextField();
        item3 = new javax.swing.JTextField();
        item4 = new javax.swing.JTextField();
        vr1 = new javax.swing.JTextField();
        vr2 = new javax.swing.JTextField();
        vr3 = new javax.swing.JTextField();
        vr4 = new javax.swing.JTextField();
        btn_Limpiar = new pruebas.RSButton();
        btn_Imprimir = new pruebas.RSButton();
        rSDateChooser1 = new rojeru_san.rsdate.RSDateChooser();
        rSLabelTextIcon1 = new RSMaterialComponent.RSLabelTextIcon();
        rSLabelDropcap1 = new rojeru_san.rslabel.RSLabelDropcap();
        rSLabelBorderRound1 = new rojeru_san.rslabel.RSLabelBorderRound();
        rSLabelAnimated1 = new rojeru_san.rslabel.RSLabelAnimated();
        rSLabelDropcap2 = new rojeru_san.rslabel.RSLabelDropcap();
        rSLabelDropcap3 = new rojeru_san.rslabel.RSLabelDropcap();
        rSLabelBorderRound2 = new rojeru_san.rslabel.RSLabelBorderRound();
        fact = new RSComponentShade.RSToggleButtonRippleShade();

        setClosable(true);
        setIconifiable(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cedulaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 111, 259, -1));
        jPanel1.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 148, 259, -1));
        jPanel1.add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 184, 259, -1));
        jPanel1.add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 220, 259, -1));

        jLabel8.setText("Producto:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 252, -1, -1));

        jLabel13.setText("VR. Unitario:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 252, -1, -1));

        jLabel18.setText("Cantidad:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 252, -1, -1));

        Cant1.setText("0");
        jPanel1.add(Cant1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 308, 46, -1));

        Cant2.setText("0");
        jPanel1.add(Cant2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 348, 46, -1));

        Cant3.setText("0");
        jPanel1.add(Cant3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 388, 46, -1));

        Cant4.setText("0");
        jPanel1.add(Cant4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 428, 46, -1));
        jPanel1.add(item5, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 463, 63, -1));

        vr5.setText("0");
        jPanel1.add(vr5, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 463, 97, -1));

        Cant5.setText("0");
        jPanel1.add(Cant5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 463, 46, -1));
        jPanel1.add(item1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 308, 63, -1));
        jPanel1.add(item2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 348, 63, -1));
        jPanel1.add(item3, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 388, 63, -1));
        jPanel1.add(item4, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 428, 63, -1));

        vr1.setText("0");
        jPanel1.add(vr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 308, 97, -1));

        vr2.setText("0");
        jPanel1.add(vr2, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 348, 97, -1));

        vr3.setText("0");
        jPanel1.add(vr3, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 388, 97, -1));

        vr4.setText("0");
        jPanel1.add(vr4, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 428, 97, -1));

        btn_Limpiar.setText("Limpiar");
        jPanel1.add(btn_Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 547, -1, -1));

        btn_Imprimir.setText("Imprimir");
        btn_Imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ImprimirActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Imprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 547, -1, -1));
        jPanel1.add(rSDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 23, -1, -1));

        rSLabelTextIcon1.setText("NIT Cliente");
        jPanel1.add(rSLabelTextIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 101, 125, -1));

        rSLabelDropcap1.setText("Direccion del cliente:");
        jPanel1.add(rSLabelDropcap1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 220, 152, 23));

        rSLabelBorderRound1.setText("Fecha:");
        jPanel1.add(rSLabelBorderRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 23, 58, -1));

        rSLabelAnimated1.setText("Favor de no dejar espacios vacios...");
        jPanel1.add(rSLabelAnimated1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 498, 348, -1));

        rSLabelDropcap2.setText("Nombre del Cliente:");
        jPanel1.add(rSLabelDropcap2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 148, 152, 23));

        rSLabelDropcap3.setText("Telefono del cliente:");
        jPanel1.add(rSLabelDropcap3, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 184, 152, 23));

        rSLabelBorderRound2.setText("Numero de factura: ");
        jPanel1.add(rSLabelBorderRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 23, 152, -1));

        fact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factActionPerformed(evt);
            }
        });
        jPanel1.add(fact, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 23, 158, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void factActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_factActionPerformed

    private void txt_cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cedulaActionPerformed
    String cedula = txt_cedula.getText().trim();
    Ctrl_Registro consultacedula = new Ctrl_Registro();
    Cliente cliente = new Cliente();
    if (cedula == "" || cedula == null){
        JOptionPane.showMessageDialog(null, "Por favor ingrese cedula");
    } else {
       cliente =  consultacedula.consultaCedula(cedula);
        if (cliente == null){
            JOptionPane.showMessageDialog(null, "Cedula no se encuentra registrada");
        } else {
            txt_name.setText(cliente.getNombres());
            txt_telefono.setText(cliente.getTelefono());
            txt_direccion.setText(cliente.getDireccion());
        }
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cedulaActionPerformed

    private void btn_ImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ImprimirActionPerformed
        total total = new total();
        total.setVisible(true);
    }//GEN-LAST:event_btn_ImprimirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cant1;
    private javax.swing.JTextField Cant2;
    private javax.swing.JTextField Cant3;
    private javax.swing.JTextField Cant4;
    private javax.swing.JTextField Cant5;
    private pruebas.RSButton btn_Imprimir;
    private pruebas.RSButton btn_Limpiar;
    private RSComponentShade.RSToggleButtonRippleShade fact;
    private javax.swing.JTextField item1;
    private javax.swing.JTextField item2;
    private javax.swing.JTextField item3;
    private javax.swing.JTextField item4;
    private javax.swing.JTextField item5;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private rojeru_san.rsdate.RSDateChooser rSDateChooser1;
    private rojeru_san.rslabel.RSLabelAnimated rSLabelAnimated1;
    private rojeru_san.rslabel.RSLabelBorderRound rSLabelBorderRound1;
    private rojeru_san.rslabel.RSLabelBorderRound rSLabelBorderRound2;
    private rojeru_san.rslabel.RSLabelDropcap rSLabelDropcap1;
    private rojeru_san.rslabel.RSLabelDropcap rSLabelDropcap2;
    private rojeru_san.rslabel.RSLabelDropcap rSLabelDropcap3;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon1;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_telefono;
    private rojeru_san.efectos.ValoresEnum valoresEnum1;
    private javax.swing.JTextField vr1;
    private javax.swing.JTextField vr2;
    private javax.swing.JTextField vr3;
    private javax.swing.JTextField vr4;
    private javax.swing.JTextField vr5;
    // End of variables declaration//GEN-END:variables
}
