/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.Ctrl_Administrador;
import controlador.Ctrl_Registro;
import controlador.Ctrl_Usuario;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import modelos.Registro;

/**
 *
 * @author USUARIO
 */
public class Login extends javax.swing.JFrame {

    public Login() {
        initComponents();
        this.setTitle("Iniciar Sesion");
        this.setLocation(450,125);
        this.setSize(new Dimension(460, 460));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rSPanelImage1 = new rojeru_san.rspanel.RSPanelImage();
        rSLabelHora1 = new rojeru_san.rsdate.RSLabelHora();
        txt_Usuario = new rojeru_san.rsfield.RSTextField();
        rSButtonCustomIcon1 = new RSMaterialComponent.RSButtonCustomIcon();
        password = new RSMaterialComponent.RSPasswordIconDos();
        btn_Recuperar = new rojeru_san.rsbutton.RSButtonEffect();
        btn_Ingresar = new rojeru_san.rsbutton.RSButtonEffect();
        btn_Salir = new rojeru_san.rsbutton.RSButtonEffect();
        btn_Registrar = new rojeru_san.rsbutton.RSButtonEffect();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout rSPanelImage1Layout = new javax.swing.GroupLayout(rSPanelImage1);
        rSPanelImage1.setLayout(rSPanelImage1Layout);
        rSPanelImage1Layout.setHorizontalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        rSPanelImage1Layout.setVerticalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jPanel1.add(rSPanelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 180, 110));
        jPanel1.add(rSLabelHora1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 9, -1, -1));

        txt_Usuario.setForeground(new java.awt.Color(0, 0, 0));
        txt_Usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Usuario.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_Usuario.setPhColor(new java.awt.Color(0, 0, 0));
        txt_Usuario.setPlaceholder("Escribe tu usuario");
        txt_Usuario.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txt_Usuario.setSelectionColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(txt_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, 50));

        rSButtonCustomIcon1.setText("Usuario");
        rSButtonCustomIcon1.setColorIcon(new java.awt.Color(0, 0, 0));
        rSButtonCustomIcon1.setColorMaterial(new java.awt.Color(0, 0, 0));
        jPanel1.add(rSButtonCustomIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 110, 50));

        password.setForeground(new java.awt.Color(0, 0, 0));
        password.setBorderColor(new java.awt.Color(0, 0, 0));
        password.setColorIcon(new java.awt.Color(0, 0, 0));
        password.setPhColor(new java.awt.Color(0, 0, 0));
        password.setPlaceholder("password");
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 370, -1));

        btn_Recuperar.setBackground(new java.awt.Color(102, 102, 255));
        btn_Recuperar.setForeground(new java.awt.Color(0, 0, 0));
        btn_Recuperar.setText("Recuperar contraseña");
        btn_Recuperar.setColorHover(new java.awt.Color(255, 255, 255));
        btn_Recuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RecuperarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Recuperar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 180, -1));

        btn_Ingresar.setBackground(new java.awt.Color(102, 102, 255));
        btn_Ingresar.setForeground(new java.awt.Color(0, 0, 0));
        btn_Ingresar.setText("Ingresar");
        btn_Ingresar.setColorHover(new java.awt.Color(255, 255, 255));
        btn_Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 170, -1));

        btn_Salir.setBackground(new java.awt.Color(102, 102, 255));
        btn_Salir.setForeground(new java.awt.Color(0, 0, 0));
        btn_Salir.setText("Salir");
        btn_Salir.setColorHover(new java.awt.Color(255, 255, 255));
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 170, -1));

        btn_Registrar.setBackground(new java.awt.Color(102, 102, 255));
        btn_Registrar.setForeground(new java.awt.Color(0, 0, 0));
        btn_Registrar.setText("Registrar");
        btn_Registrar.setColorHover(new java.awt.Color(255, 255, 255));
        btn_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 180, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_RecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RecuperarActionPerformed
        FrmRecuperar recuperar = new FrmRecuperar();
        recuperar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_RecuperarActionPerformed

    private void btn_IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IngresarActionPerformed
//        this.Login();
        Registro registro = new Registro();
        Registrar frmRegistrar = new Registrar();
        Ctrl_Registro consultar_usuario = new Ctrl_Registro();
        Ctrl_Administrador admin = new Ctrl_Administrador();
        String usuario,clave;
        usuario = this.txt_Usuario.getText();
        clave = this.password.getText();
        Ctrl_Usuario ctrl = new Ctrl_Usuario(registro, consultar_usuario, frmRegistrar, admin);
        if(ctrl.Login(usuario,clave)){
            this.txt_Usuario.setText("");
            this.password.setText("");
            Menu menu = new Menu();
            menu.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btn_IngresarActionPerformed

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_SalirActionPerformed

    private void btn_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegistrarActionPerformed
        Registrar registrar = new Registrar();
        registrar.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_RegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
                
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.rsbutton.RSButtonEffect btn_Ingresar;
    private rojeru_san.rsbutton.RSButtonEffect btn_Recuperar;
    private rojeru_san.rsbutton.RSButtonEffect btn_Registrar;
    private rojeru_san.rsbutton.RSButtonEffect btn_Salir;
    private javax.swing.JPanel jPanel1;
    private RSMaterialComponent.RSPasswordIconDos password;
    private RSMaterialComponent.RSButtonCustomIcon rSButtonCustomIcon1;
    private rojeru_san.rsdate.RSLabelHora rSLabelHora1;
    private rojeru_san.rspanel.RSPanelImage rSPanelImage1;
    private rojeru_san.rsfield.RSTextField txt_Usuario;
    // End of variables declaration//GEN-END:variables
//    private void Login(){              
//        if(!txt_Usuario.getText().isEmpty() && !password.getText().isEmpty()){
//            Ctrl_Administrador controlAdministrador = new Ctrl_Administrador();
//            Registro admin = new Registro();
//            admin.setNombre(txt_Usuario.getText().trim());
//            admin.setPassword(password.getText().trim());
//            if(controlAdministrador.loginUser(admin)){
//                JOptionPane.showMessageDialog(null, "Usuario Correcto");
//                Menu menu = new Menu();
//                menu.setVisible(true);
//                this.dispose();
//            }else{
//                JOptionPane.showMessageDialog(null, "Usuario o clave incorrectos");                
//            }
//        }else{
//            JOptionPane.showMessageDialog(null, "Ingrese sus Datos");
//        }
//    }
}

