/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controlador.Ctrl_Administrador;
import controlador.Ctrl_Registro;
import controlador.Ctrl_Usuario;
import controlador.controlador;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import modelos.Registro;

/**
 *
 * @author braya
 */
public class Registrar extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Registrar() {
        initComponents();
        this.setTitle("Registrar");
        this.setLocation(450,125);
        this.setSize(new Dimension(500, 450));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rSLabelTextIcon1 = new RSMaterialComponent.RSLabelTextIcon();
        txt_Correo = new rojeru_san.rsfield.RSTextField();
        Password = new RSMaterialComponent.RSPasswordIconDos();
        btn_Volver = new rojeru_san.rsbutton.RSButtonEffect();
        rSButtonCustomIcon3 = new RSMaterialComponent.RSButtonCustomIcon();
        btn_Registrar = new rojeru_san.rsbutton.RSButtonEffect();
        txt_Usuario = new rojeru_san.rsfield.RSTextField();
        rSButtonCustomIcon4 = new RSMaterialComponent.RSButtonCustomIcon();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSLabelTextIcon1.setForeground(new java.awt.Color(0, 0, 0));
        rSLabelTextIcon1.setText("Resgistrar");
        rSLabelTextIcon1.setColorIcon(new java.awt.Color(0, 0, 0));
        rSLabelTextIcon1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jPanel1.add(rSLabelTextIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 260, 60));

        txt_Correo.setForeground(new java.awt.Color(0, 0, 0));
        txt_Correo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Correo.setPhColor(new java.awt.Color(0, 0, 0));
        txt_Correo.setPlaceholder("Escribe algo");
        txt_Correo.setSelectionColor(new java.awt.Color(0, 0, 0));
        txt_Correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CorreoActionPerformed(evt);
            }
        });
        jPanel1.add(txt_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 290, 50));

        Password.setForeground(new java.awt.Color(0, 0, 0));
        Password.setBorderColor(new java.awt.Color(0, 0, 0));
        Password.setColorIcon(new java.awt.Color(0, 0, 0));
        Password.setPhColor(new java.awt.Color(0, 0, 0));
        Password.setPlaceholder("password");
        Password.setSelectionColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 410, -1));

        btn_Volver.setBackground(new java.awt.Color(102, 102, 255));
        btn_Volver.setForeground(new java.awt.Color(0, 0, 0));
        btn_Volver.setText("Volver");
        btn_Volver.setColorHover(new java.awt.Color(255, 255, 255));
        btn_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VolverActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 140, -1));

        rSButtonCustomIcon3.setText("Email");
        rSButtonCustomIcon3.setColorIcon(new java.awt.Color(0, 0, 0));
        rSButtonCustomIcon3.setColorMaterial(new java.awt.Color(0, 0, 0));
        rSButtonCustomIcon3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonCustomIcon3ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonCustomIcon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 110, 50));

        btn_Registrar.setBackground(new java.awt.Color(102, 102, 255));
        btn_Registrar.setForeground(new java.awt.Color(0, 0, 0));
        btn_Registrar.setText("Registrar");
        btn_Registrar.setColorHover(new java.awt.Color(255, 255, 255));
        btn_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, -1, -1));

        txt_Usuario.setForeground(new java.awt.Color(0, 0, 0));
        txt_Usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Usuario.setPhColor(new java.awt.Color(0, 0, 0));
        txt_Usuario.setPlaceholder("Escribe algo");
        txt_Usuario.setSelectionColor(new java.awt.Color(0, 0, 0));
        txt_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_UsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txt_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 290, 50));

        rSButtonCustomIcon4.setText("Usuario");
        rSButtonCustomIcon4.setColorIcon(new java.awt.Color(0, 0, 0));
        rSButtonCustomIcon4.setColorMaterial(new java.awt.Color(0, 0, 0));
        rSButtonCustomIcon4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonCustomIcon4ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonCustomIcon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 110, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_CorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CorreoActionPerformed

    private void btn_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VolverActionPerformed
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_VolverActionPerformed

    private void rSButtonCustomIcon3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonCustomIcon3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonCustomIcon3ActionPerformed

    private void btn_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegistrarActionPerformed
        Registro registro = new Registro();
        Registrar frmRegistrar = new Registrar();
        Ctrl_Registro consultar_usuario = new Ctrl_Registro();
        Ctrl_Administrador admin = new Ctrl_Administrador();
        String usuario,correo,clave;
        usuario = this.txt_Usuario.getText();
        correo = this.txt_Correo.getText();
        clave = this.Password.getText();
        Ctrl_Usuario ctrl = new Ctrl_Usuario(registro, consultar_usuario, frmRegistrar, admin);
        ctrl.Guardar(usuario, correo, clave);
//          if(ctrl.Guardar(usuario, correo, clave)){
//              this.txt_Usuario.setText("");
//              
//          }
          
//        Registro registro = new Registro();    
//        Ctrl_Registro controlRegistro = new Ctrl_Registro();
//        registro.setNombre(txt_Usuario.getText().trim());
//        registro.setPassword(Password.getText().trim());
//        registro.setCorreo(txt_Correo.getText().trim());
//        
//        if (txt_Usuario.getText().isEmpty()&& Password.getText().isEmpty()&& txt_Correo.getText().isEmpty()){
//            JOptionPane.showMessageDialog(null, "Complete todos los campos");
//        } else {
//            if (!controlRegistro.exitePassword(txt_Usuario.getText().trim())) {
//                registro.setNombre(txt_Usuario.getText().trim());
//                registro.setPassword(Password.getText().trim());
//                registro.setCorreo(txt_Correo.getText().trim());
//                if (controlRegistro.Registrar(registro)) {
//                    JOptionPane.showMessageDialog(null, "Registro Guardado");
//                } else {
//                    JOptionPane.showMessageDialog(null, "Error al Guardar");
//                }
//            } else {
//                JOptionPane.showMessageDialog(null, "ya existe en la base de datos");
//            }
//
//        }
//        txt_Usuario.setText("");
    }//GEN-LAST:event_btn_RegistrarActionPerformed

    private void txt_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_UsuarioActionPerformed

    private void rSButtonCustomIcon4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonCustomIcon4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonCustomIcon4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public RSMaterialComponent.RSPasswordIconDos Password;
    public rojeru_san.rsbutton.RSButtonEffect btn_Registrar;
    private rojeru_san.rsbutton.RSButtonEffect btn_Volver;
    private javax.swing.JPanel jPanel1;
    private RSMaterialComponent.RSButtonCustomIcon rSButtonCustomIcon3;
    private RSMaterialComponent.RSButtonCustomIcon rSButtonCustomIcon4;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon1;
    public rojeru_san.rsfield.RSTextField txt_Correo;
    public rojeru_san.rsfield.RSTextField txt_Usuario;
    // End of variables declaration//GEN-END:variables
}
