
package vistas;

public class total extends javax.swing.JFrame {

 
    public total() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        facturaa1 = new javax.swing.JTextField();
        dates1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        cedu1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        nombrec1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        domis1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        celu1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        ite6 = new javax.swing.JTextField();
        ite7 = new javax.swing.JTextField();
        ite8 = new javax.swing.JTextField();
        ite9 = new javax.swing.JTextField();
        ite10 = new javax.swing.JTextField();
        c6 = new javax.swing.JTextField();
        c7 = new javax.swing.JTextField();
        c8 = new javax.swing.JTextField();
        c9 = new javax.swing.JTextField();
        c10 = new javax.swing.JTextField();
        v6 = new javax.swing.JTextField();
        v7 = new javax.swing.JTextField();
        v8 = new javax.swing.JTextField();
        v9 = new javax.swing.JTextField();
        v10 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        t8 = new javax.swing.JTextField();
        t9 = new javax.swing.JTextField();
        t10 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        top1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        rSPanelImage1 = new rojeru_san.rspanel.RSPanelImage();
        btn_Menu = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setText("La Mayorista");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 13, 88, 35));

        jLabel18.setText("FACTURA");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 13, 173, 35));

        jLabel19.setText("av 3#8-32 Doña Nidia");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 55, -1, -1));

        jLabel20.setText("Cucuta, N. Santander");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 79, 125, -1));

        jLabel21.setText("3222825602");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 106, 111, -1));

        jLabel22.setBackground(new java.awt.Color(153, 0, 153));
        jLabel22.setForeground(new java.awt.Color(0, 0, 204));
        jLabel22.setText("Factura #                              Fecha:");
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 78, 224, -1));

        facturaa1.setEnabled(false);
        getContentPane().add(facturaa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 103, 94, -1));

        dates1.setEnabled(false);
        getContentPane().add(dates1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 103, 87, -1));

        jLabel23.setForeground(new java.awt.Color(0, 0, 204));
        jLabel23.setText("c.c. del Cliente:                      Terminos:");
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 138, 220, -1));

        cedu1.setEnabled(false);
        getContentPane().add(cedu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 163, 104, -1));

        jLabel24.setText("contra entrega");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 166, -1, -1));

        jLabel25.setText("Nombre del Cliente:");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 192, 111, -1));

        nombrec1.setEnabled(false);
        getContentPane().add(nombrec1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 215, 125, -1));

        jLabel26.setText("Direccion del Cliente:");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 250, 125, -1));

        domis1.setEnabled(false);
        getContentPane().add(domis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 273, 125, -1));

        jLabel27.setText("Telefono del Cliente:");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 192, 116, -1));

        celu1.setEnabled(false);
        getContentPane().add(celu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 215, 126, -1));

        jLabel28.setText("Producto:");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 359, 75, 26));

        jLabel29.setText("Cantidad:");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 359, 64, 26));

        jLabel30.setText("VR. Unitario:");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 359, 66, 26));

        jLabel31.setText("Total:");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 359, 90, 26));

        ite6.setEnabled(false);
        getContentPane().add(ite6, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 407, 87, -1));

        ite7.setEnabled(false);
        getContentPane().add(ite7, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 442, 87, -1));

        ite8.setEnabled(false);
        getContentPane().add(ite8, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 477, 87, -1));

        ite9.setEnabled(false);
        getContentPane().add(ite9, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 512, 87, -1));

        ite10.setEnabled(false);
        getContentPane().add(ite10, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 547, 87, -1));

        c6.setEnabled(false);
        getContentPane().add(c6, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 407, 52, -1));

        c7.setEnabled(false);
        getContentPane().add(c7, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 442, 52, -1));

        c8.setEnabled(false);
        getContentPane().add(c8, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 477, 52, -1));

        c9.setEnabled(false);
        getContentPane().add(c9, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 512, 52, -1));

        c10.setEnabled(false);
        getContentPane().add(c10, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 547, 52, -1));

        v6.setEnabled(false);
        getContentPane().add(v6, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 407, 91, -1));

        v7.setEnabled(false);
        getContentPane().add(v7, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 442, 91, -1));

        v8.setEnabled(false);
        getContentPane().add(v8, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 477, 91, -1));

        v9.setEnabled(false);
        getContentPane().add(v9, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 512, 91, -1));

        v10.setEnabled(false);
        getContentPane().add(v10, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 547, 91, -1));

        t6.setEnabled(false);
        getContentPane().add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 407, 90, -1));

        t7.setEnabled(false);
        getContentPane().add(t7, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 442, 90, -1));

        t8.setEnabled(false);
        getContentPane().add(t8, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 512, 90, -1));

        t9.setEnabled(false);
        getContentPane().add(t9, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 477, 90, -1));

        t10.setEnabled(false);
        getContentPane().add(t10, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 547, 90, -1));

        jLabel32.setText("TOTAL A PAGAR:");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 586, 102, 32));

        top1.setEnabled(false);
        getContentPane().add(top1, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 582, 185, 40));

        jButton2.setText("Crear Factura Nueva");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 629, 155, -1));

        javax.swing.GroupLayout rSPanelImage1Layout = new javax.swing.GroupLayout(rSPanelImage1);
        rSPanelImage1.setLayout(rSPanelImage1Layout);
        rSPanelImage1Layout.setHorizontalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        rSPanelImage1Layout.setVerticalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        getContentPane().add(rSPanelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 180, 110));

        btn_Menu.setText("Menu");
        btn_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MenuActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MenuActionPerformed
//        Menu menu = new Menu();
//        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_MenuActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(total.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(total.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(total.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(total.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new total().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Menu;
    public static javax.swing.JTextField c10;
    public static javax.swing.JTextField c6;
    public static javax.swing.JTextField c7;
    public static javax.swing.JTextField c8;
    public static javax.swing.JTextField c9;
    public static javax.swing.JTextField cedu1;
    public static javax.swing.JTextField celu1;
    public static javax.swing.JTextField dates1;
    public static javax.swing.JTextField domis1;
    public static javax.swing.JTextField facturaa1;
    public static javax.swing.JTextField ite10;
    public static javax.swing.JTextField ite6;
    public static javax.swing.JTextField ite7;
    public static javax.swing.JTextField ite8;
    public static javax.swing.JTextField ite9;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    public static javax.swing.JTextField nombrec1;
    private rojeru_san.rspanel.RSPanelImage rSPanelImage1;
    public static javax.swing.JTextField t10;
    public static javax.swing.JTextField t6;
    public static javax.swing.JTextField t7;
    public static javax.swing.JTextField t8;
    public static javax.swing.JTextField t9;
    public static javax.swing.JTextField top1;
    public static javax.swing.JTextField v10;
    public static javax.swing.JTextField v6;
    public static javax.swing.JTextField v7;
    public static javax.swing.JTextField v8;
    public static javax.swing.JTextField v9;
    // End of variables declaration//GEN-END:variables
}
